River-iGaming/workflows

- .github/workflows/frontend-build-and-publish-apps.yml
- .github/workflows/frontend-build-and-publish-libs.yml
- .github/workflows/frontend-build-and-tag-configs.yml
https://riverigaming.atlassian.net/browse/RTFE-5983
> fix(frontend): push only created tag

- .github/workflows/frontend-build-and-publish-apps.yml
- .github/workflows/frontend-build-and-publish-libs.yml
https://riverigaming.atlassian.net/browse/RTFE-5983
> fix(frontend): fail job if tag exists

- .github/workflows/frontend-build-and-publish-apps.yml
https://riverigaming.atlassian.net/browse/RTFE-5983
> fix(frontend): get last commit sha

- .github/workflows/frontend-build-and-publish-apps.yml
- .github/workflows/frontend-build-and-publish-libs.yml
https://riverigaming.atlassian.net/browse/RTFE-6685
> feat(frontend):  cancel any in-progress job or run

- .github/workflows/frontend-build-and-publish-apps.yml
Issue: https://rivertechplc.slack.com/archives/GGN5P6R7D/p1657720727414709
> feat(frontend): branch name in app version

- .github/workflows/frontend-build-and-publish-apps.yml
- .github/workflows/frontend-build-and-tag-configs.yml
prefix tag with `-vnext` when checking on `vnext` branch
> fix(frontend): tag prefix for vnext

- .github/workflows/frontend-build-and-publish-apps.yml
https://rivertechplc.slack.com/archives/G010QGNM754/p1690963458514619
Tested on JB
> fix(frontend build and publish apps): fail downmerge when conflicts

- .github/workflows/node-libs.yml
https://github.com/River-iGaming/midgard.ngx/actions/runs/5978443745/job/16220552768
Testing: https://github.com/River-iGaming/midgard.ngx/pull/536
Successful Test run: https://github.com/River-iGaming/midgard.ngx/actions/runs/5997898468/job/16270251750
> fix(node libs): support multiline commit message

- .github/workflows/node-libs.yml
https://github.com/River-iGaming/workflows/pull/58
misread https://stackoverflow.com/a/74887073 and did them inverted...
> fix(node libs): marker not set for multiline commit message

- .github/workflows/node-libs.yml
re apply the fix from https://github.com/River-iGaming/workflows/pull/56/files
> fix(node libs): escape commit msg backticks

- .github/workflows/check-node-version-bump.yml
- .github/workflows/frontend-build-and-publish-apps.yml
https://rivertechnologies.atlassian.net/browse/RTFE-6521
> feat(*): check version bump on master prs

- .github/workflows/frontend-build-and-publish-apps.yml
https://rivertechplc.slack.com/archives/G010QGNM754/p1697017867691479
> chore(build and publish): upgrade actions/setup-dotnet

- .github/workflows/node-libs.yml
To check build on:
- [event === branch] https://github.com/River-iGaming/midgard.white-label/tree/feature/workflow-joseph
- [event === pull_request] https://github.com/River-iGaming/midgard.white-label/pull/3445
> fix(node libs): environment variables not sanitized

- .github/workflows/node-libs.yml
To check build on PR https://github.com/River-iGaming/midgard.white-label/pull/3446
PR https://github.com/River-iGaming/midgard.white-label/actions/runs/6614411396/job/17964331078?pr=3446
Push https://github.com/River-iGaming/midgard.white-label/actions/runs/6614411055/job/17964330178?pr=3446
> fix(node libs): get PR title instead of commit message

- .github/workflows/downmerge-releases.yml
found here https://github.com/River-iGaming/azurolongo.prive/actions/runs/7019301146/job/19096443328 in Downmerge block the following error:
```
/home/runner/work/_temp/1705df8b-eeaa-4c82-84f5-382dfeecfc8e.sh: line 50: MANUAL_MERGE: command not found
```
> fix(downmerge): MANUAL_MERGE: command not found

- .github/workflows/dotnet-microservice.yml
fixes: https://github.com/Innovio-Technologies/ebisu.tenjin/actions/runs/9283317807/job/25543276032
> feat(dotnet ms): add optional docker compose path

- .github/workflows/frontend-build-and-publish-apps.yml
unable to replicate, adding verbose to all
> feat(frontend build app): add verbose flag on dotnet restore

- .github/workflows/frontend-build-and-publish-apps.yml
This reverts commit b4a198b97ff9dc2e973618051d638b2b1f18ad50.
> revert(frontend build app): add verbose flag on dotnet restore

- .github/workflows/frontend-build-and-publish-apps.yml
- ci tooling seems unused (and tested in olympe) which is 30-45sec extra
> feat(frontend apps build): concurrency adjust + remove odin ci tooling

- .github/workflows/node-libs.yml
should fix issue: https://github.com/River-iGaming/odin.ngx/actions/runs/12934075936/job/36074205440
> feat(node-libs): update upload-artifacts to v4

- .github/workflows/downmerge-releases.yml
https://rivertechplc.slack.com/archives/G010QGNM754/p1739521411241519
* `release/1.9.x` with `1.9.0-prerelease` version - failed https://github.com/River-iGaming/whitelabel-test-workflow/actions/runs/13331443201/job/37236280055
* `release/1.10.x` with`1.10.0` version - passed https://github.com/River-iGaming/whitelabel-test-workflow/actions/runs/13331484277/job/37236420033
> fix(downmerge): do not allow downmerge for prerelease

- .github/workflows/dotnet-libs.yml
- .github/workflows/dotnet-microservice.yml
- .github/workflows/java-publish-nugets.yml
- **v3**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **update branch ordering**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **sp**
- **g**
- **g**
- **g**
- **g**
- **multi project support**
- **dryrun image build**
- **version -> tag**
- **dry-run mode flag**
> feat(dotnet-microservices): multiplatform build support for mw services (INFRA-2012)"

- .github/workflows/node-libs.yml
https://rivertechnologies.atlassian.net/browse/FEBO-2342
> feat(node-libs): support pnpm

- .github/workflows/downmerge-releases.yml
- README.md
https://rivertechnologies.atlassian.net/browse/RTVX-343
* downmerge fail - https://github.com/River-iGaming/whitelabel-test-workflow/actions/runs/15140452395/job/42562839246
* downmerge fail - not allowed commit type https://github.com/River-iGaming/whitelabel-test-workflow/actions/runs/15140462995/job/42562866804
* downmerge passed https://github.com/River-iGaming/whitelabel-test-workflow/actions/runs/15140547996/job/42563191369
* autoresolve https://github.com/River-iGaming/whitelabel-test-workflow/actions/runs/15140612123/job/42563423013
> fix(downmerge): configured base branch and support new flow
